# INTRODUCTION TO NUMPY
**USE BELOW LINK TO READ MORE ON NUMPY.....:**

[CLICK_NUMPY_PDF](https://numpy.org/doc/1.23/numpy-user.pdf)

[official_numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

### WHY NUMPY ?
* IT'S FASTER THAN PYTHON ARRAY(SPEED IS HIGHER THAN PYTHON ARRAY)
* PYTHON ARRAY REQUIRED MORE SPACE THAN NUMPY (AS ITS RETURN IN C)
* IT'S USED IN BIG DATA FOR ANALYSIS
* NUMPY IS NUMERICAL COMPUTATIONAL ANALYSIS.....

use this link to read more about numpy...
[numpy..attributes](https://www.educative.io/answers/what-are-the-most-important-attributes-of-a-numpy-array-object)

In [1]:
#Importing numpy to jupyter
#Don't use from as there might be class in functon of diff modules
#use tab to autosuugest command
import numpy as np

In [2]:
#CREATING OF FIRST NUMPY ARRAY
#SYNTAX: NP.ARRAY(LIST)
l1 = np.array([1,2,3,4,5,6]) 
print(l1, type(l1),sep="................")
#NP.TYPE IS ARRAY AS ITS RETURN IN C & HAS HOMOGENOUS ITEMS ALWAYS

[1 2 3 4 5 6]................<class 'numpy.ndarray'>


In [3]:
#shape: This attribute returns the dimension of the array. 
#It is a tuple of integers that indicates the size of your NumPy array.
#eg: its a matrix of 4-rows & 3-col
#Note: no of element in all row must be same
l2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(l2.shape)



(4, 3)


In [4]:
#dtype:to check what type of elements are stored in the NumPy array.
#if there is even a single val float then it will return float64 
print(l2.dtype)


int32


In [5]:
#creating blanks array with all element zeros
#SYNTAX: np.zeros(tuple(rows,column)) is madatory
k = np.zeros((4,6))
print(k)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
#creating blank array with all element ones
#SYNTAX: np.ones(tuple(rows,column))
k1 = np.ones((3,5))
print(k1)

#Note: TO GET ALL VALUE 'N' AS INTEGER MULTIPLY (NP.ONES()) * 'N'

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
#creating an empty array 
#it look similar to zeros but it can have garbage value
k2 = np.empty((4,3))
print(k2)

[[6.23042070e-307 3.56043053e-307 1.60219306e-306]
 [2.44763557e-307 1.69119330e-306 1.78022342e-306]
 [1.05700345e-307 3.11525958e-307 1.69118108e-306]
 [8.06632139e-308 1.20160711e-306 1.69119330e-306]]


### IMPORTANT PROPERTIES OF NUMPY
* the operation applied on one element will perform same operation on al the element

In [8]:
#NOTE: TO ACCESS ALL FUNCTION IN NUMPY USE FOLLOWING CMND
#THERE ARE 614 FUNCTONS
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [9]:
lst1 = np.array([[1,2],[3,4]])

1. **SQUARES OF VALUE**

In [10]:
#square of each elements
#it will square each value in the array
#even if we multiply directly it will give product of each value
sq1 = lst1**2
#numpy array multiplication will be diff from matrix multiplication
sq2 = lst1*lst1
print(sq1,sq2,sep="\n")

[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]


2. **MULTIPLICATION WITH CONSTANT**

In [11]:
str1 = "multiplication with scalar"
k = 3
m1 = lst1*k
print(str1,m1,sep="\n")


multiplication with scalar
[[ 3  6]
 [ 9 12]]


3. **ADDITION/SUBTRACTION WITH CONST OR ITSELF**

In [12]:
#USE +- SIGN AS PER REQUIREMENT IT WILL FUNCTION IN A SIMILAR MANNER
lst2 = np.array([[1,2],[3,4]])
A = lst2 + lst2
print(A)
print(lst2)
B = lst2 + 3
print(B)

[[2 4]
 [6 8]]
[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


4. **INVERSE OF ARRAY ELEMENT**

In [13]:
ls3 = np.array([[1,10],[4,5]])
print(1/ls3)

[[1.   0.1 ]
 [0.25 0.2 ]]


5. **SLICING**

In [14]:
#IT'S BETTER TO COPY AND USE TO PERFORM BETTER OPERATION
#AS IT WILL POINT TO THE SAME ARRAY IN THE MEMORY LOCATION
#as shown in the eg the same array is used and the chane in sliced array will change the origibnal array

ls3 = np.array([1,2,3,4,5])
print(ls3)
print(ls3[2])
arr1 = ls3[3:]
print(arr1)
arr1[0] = 7
print(ls3)
print("*"*20)

#performing operation after copy
ls4 = np.array([1,2,3,4,5])
print(ls4)
arr2 = ls4[3:].copy()
print(arr2)
arr2[0] = 9
print(arr2)
print(ls4)

[1 2 3 4 5]
3
[4 5]
[1 2 3 7 5]
********************
[1 2 3 4 5]
[4 5]
[9 5]
[1 2 3 4 5]


6. **MASKING OR FANCY INDEXING**

In [15]:
# ITS USED FOR BOOLEAN INDEXING AND CAN GIVE INDEX AS PER CONDITION
ls1 = np.arange(15).reshape(3,5)
print(ls1)
print()
print(ls1 > 2)
print()
a = ls1[ls1 > 5]  #it will give op in 1d format only
print(a)
print()

#using multiple condition
b = ls1[(ls1%2==0) | (ls1%3) == 0]
print(b)  #it will give index of contn following element
print()
print((ls1%2==0) | (ls1%3) == 0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

[ 6  7  8  9 10 11 12 13 14]

[3 9]

[[False False False  True False]
 [False False False False  True]
 [False False False False False]]


7. **ACCESSING ELEMENT IN AN ARRAY**

In [16]:
#ACCESSING IN  A 1D NUMPY ARRAY
l1 = np.array([1,2,3,4,5])
print(l1[2])
print(l1[3])
print()
print("*"*10)

#ACCESSING IN A 'N' DIMENSION NUMPY ARRAY
l2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l2[1,2])
print(l2[1][2])
print(l2[0])
print()
print("*"*10)


#THE BELOW METHOD IS USED TO ACCESS MULTIPLE ITEMS AT A TIME
#MOST CONVENTIONAL WAY TO ACCES USING INDEXING(1-DIMENSION)
ls1 = np.array([200,500,300,600,700,450])
print(ls1)
print(ls1[[2,3,4,5]]) #it will access all the indexed element seperated by commas
print()
print("*"*10)


#MOST CONVENTIONAL WAY TO ACCES USING INDEXING(N-DIMENSION)
ls2 = np.array([[1,2,3,4],[4,3,2,1],[7,8,9,0]])
print(ls2)
print(ls2[[0,1,2],[0,0,1]]) #it will access corresponding element list[[a,b,c][a,b,c]] i.e... a=a; b=b; c=c

3
4

**********
6
6
[1 2 3]

**********
[200 500 300 600 700 450]
[300 600 700 450]

**********
[[1 2 3 4]
 [4 3 2 1]
 [7 8 9 0]]
[1 4 8]


# MORE ON NUMPY FUNCTION

1. **AXIS OR (ROW/COLUMN) WISE SUMS**

> FOR 1D MATRIX

In [17]:
#SUM OF ELEMENT IN 1D ARRAY
a1 = np.array([1,2,3,4])
print(sum(a1))

10


> FOR 2D MATRIX/ARRAY

In [18]:
#NOTE: AXIS=0 IS FOR COLUMN & AXIS=1 IS FOR ROWS
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print()
print(arr1.shape)
print()
#FOR COLUMN WISE SUM USE AXIS= 0...
#since column sum array shape is (1,3) 
# & 1 is 0th element thats why axis=0
print(arr1.sum(axis=0))
print()
print("*"*50)

#FOR ROW WISE SUM USE AXIS = 1
#since row sum array shape is (2,1) 
#&  1 is for 1st element thats'y axis = 1
k = arr1.sum(axis=1)
print(k.shape)
print(arr1.sum(axis=1))

[[1 2 3]
 [4 5 6]]

(2, 3)

[5 7 9]

**************************************************
(2,)
[ 6 15]


2. **DOT PRODUCT OF ELEMENT**

In [19]:
#FOR DOT PRODUCT NO OF ROW IN 1 == NO OF ROW IN COLUMN
#THATS WHY TRANSPOSE IS DONE
a1 =  np.array([[1,2],[3,4],[5,6]])
a2 = np.array([[7,8],[9,10],[11,12]])
ans = a1.dot(a2.transpose())
print(ans)
print("*"*50)
#OTHER SYNTAX : NP.DOT(ARR1,ARR2)
print(np.dot(a1,a2.transpose()))


[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]
**************************************************
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]


3. **CROSS PRODUCT**

In [20]:
#CROSS PRODUCT IS BEWEEN TWO VECTORS
ans = np.cross(a1,a2)
print(ans)

[-6 -6 -6]


4. **SORTING**

NOTE: DIFFERENT KIND OF SORTING ALGORITHMS IN NUMPY..
CLICK TO CHECK ALL THE ALGORITHMS
[CLICK_KIND](https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [21]:
### SORTING IN 1D ARRAY
a1 = np.array([1,7,3,5,8,2,9,6])
            #  0,1,2,3,4,5,6,7
print(np.sort(a1))
print(np.argsort(a1))  #it will return index of sorted element poition where they were befor
print("*"*50)

### SORTING IN 2D ARRAY
#syntax: np.sort(array, axis = "0 or 1", kind="sorting_type..(quicksort,mergesort..)")
a2 = np.array([[1,3,6],[5,3,2]])
print("column wise sort")
ans1 = np.sort(a2,axis=0,kind='mergesort')
print(ans1)
print("row wise sort")
ans2 = np.sort(a2,axis=1,kind='mergesort')
print(ans2)


#note: bydefault axis will be last axis or it will sort as the same order given.

[1 2 3 5 6 7 8 9]
[0 5 2 3 7 1 4 6]
**************************************************
column wise sort
[[1 3 2]
 [5 3 6]]
row wise sort
[[1 3 6]
 [2 3 5]]


7. **NUMPY ARANGE FUNCTION**`

In [22]:
##ARRANGE FUNCTION IS SIMILAR TO RANGE FUNCTION IN PYTHON
#SYNTAX: arange(start,end,step_size)
a = np.arange(10)
print(a)
print("*"*50)

###LINSPACE:ITS SIMILAR TO ARANGE BUT END_POINT IS INCLUSIVE
#SYNTAX: np.linspace(start,end, required_count)
b = np.linspace(1,100,15)
print(b)

[0 1 2 3 4 5 6 7 8 9]
**************************************************
[  1.           8.07142857  15.14285714  22.21428571  29.28571429
  36.35714286  43.42857143  50.5         57.57142857  64.64285714
  71.71428571  78.78571429  85.85714286  92.92857143 100.        ]


8. **CONVERTING ARRAY INTO N-DIMENSION & order of index**

In [23]:
#RESHAPE: its used to convert 1d to n-d matrix
#SYNTAX: arr.reshape(row_required,col_required)
#NOTE: lenght(1d array) = row_required * col_required
b = np.array([1,2,3,4,5,6,7,8,9,0])
print(b.shape)
print("*"*50)
c = b.reshape(5,2)
print(c)
print("*"*50)
print(c.shape)
print("*"*50)


#ARGSORT: it will give the index order of element present in ascending order
#IT CAN BE USE IN N_DIMENSION ARRAY
l1 = np.array([1,9,2,8,3,7,4,6,5])
print(np.argsort(l1))
print(np.argmin(l1)) #it return index of min element
print(np.argmax(l1)) #it return index of max element

(10,)
**************************************************
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]
**************************************************
(5, 2)
**************************************************
[0 2 4 6 8 7 5 3 1]
0
1


9. **CONVERTING FROM N_DIM TO 1_D ARRAY**

In [24]:
###FLATENNING: ITS USE TO CONVER N DIM INTO A 1_D ARRAY
#SYNTAX: NP.FLATTEN(LIST_NAME)
a = np.arange(12).reshape(3,4)
print(a)
b = a.flatten()
print(b)

#the above thing can also be done using reshape(n_element)
d = a.reshape(12)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### 10.TILE FUNCTION

In [37]:
#TILE FUNCTION(): IT IS USED TO COPY NUMY MATRIX IN THE REQUIRED FORM BY STACKING OVER OTHER
#SYNTAX: np.tile(array_name,(row_repeat_no,col_repeat _no))
t1 = np.arange(10).reshape(2,5)
print(t1)
print()

tile1 = np.tile(t1,(3,2))
print(tile1)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]
 [0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]
 [0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


# NUMPY MATRIX PROPERTIES

1. **DIAGONAL MATRIX**

In [26]:
#np.diag(values) : IT WILL CREATE A DIAGONAL MATRIX WITH ELEMENT GIVEN AS VALUE(TUPLES) INSIDE IT
a = np.diag((1,2,3,4))
print(a)

#diagonal of diagonal will return a 1-D array....similar to (transpose of transpose is original array)
C = np.diag(a)
print(C)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


2. **IDENTITY MATRIX**

In [27]:
## np.IDENTITY((TUPLE),dtype="datatype") WILL RETURN AN N_DIMENSION IDENTITY MATRIX
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 3.TRANSPOSE OF MATRIX

In [28]:
#TRANSPOSE('T') : IT WILL INTERCHENGE ROW NUM INTO COLUM NO
a = np.arange(1,10).reshape(3,3)
print(a)
print()

#using name.T will also convert into transpose
aT = a.T
print(aT)
print()

#using transpose function
aT1 = np.transpose(a)
print(aT1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]
